### ISSUE TITLE
About Firefox Support...

### ISSUE THREAD

**Issue by Vincent392** [datkat21/ControllerOverlays#1]
# this should be considered as Documentation, but
Firefox 115 LTS Works, without changing user agents, on Windows 8.1...
with a Dualshock 4 controller
![image](https://github.com/datkat21/ControllerOverlays/assets/90470156/7865996c-5a96-4f03-afe9-fcfb28d30125)

**Comment by datkat21** [comment]
Thanks for the insight, I'll look into this!

**Comment by datkat21** [comment]
Firefox controller support seems to work on and off for me, sometimes it picks up controllers and other times it doesn't. So I'll just say use Chrome if you want it to be reliable. Testing with XInput controllers on Firefox 120.0.1 (64-bit) under Windows 10 shows nothing at all, even on the reliable [gamepad tester](https://hardwaretester.com/gamepad) page.

Edit: I will need to try this with a DInput controller. I'll update with a new response if this worked or not.

**Comment by datkat21** [comment]
DS4 controller works natively in Firefox. Hmm. That's good to see it working

![firefox_VxOZyyXNsG](https://github.com/datkat21/ControllerOverlays/assets/49850194/61a2e7a2-8c07-4152-ac17-e302b5cc14a6)

**Comment by datkat21** [comment]
As of af6b5bd, PS4 controller support is added and tested working with Firefox and Chrome.

**Comment by datkat21** [comment]
I'll just close this now
